{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: automation-configmap
data:
  CONF_FILE: {{ .Values.env.configFile | quote }}
  DISCRETE_AGENT_DB: {{.Values.env.pg_schemas.discrete_agent_db}}
{{- end }}
