apiVersion: batch/v1
kind: CronJob
metadata:
  name: automation-ingestion-test
spec:
  #schedule: "0 0 * * *"
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
#          imagePullSecrets:
#            - name: "acr-registry"
          serviceAccountName: "cluster-automation"
          containers:
            - name: automation-ingestion-test
              image: "10.45.128.62:5000/ingestion:v1.1.3"
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: automation-ingestion-test-configmap
          restartPolicy: OnFailure
