apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-automation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: cluster-automation
roleRef:
  kind: Role
  name: cluster-automation
  apiGroup: rbac.authorization.k8s.io
